url:
  turhome: "https://www.railstutorial.org"
  turhelp: "https://www.railstutorial.org/help"
  turbook: "https://www.railstutorial.org/book"
  mich: "https://www.michaelhartl.com/"
  Learn: "https://www.learnenough.com/"
  screen: "https://screencasts.railstutorial.org/"
  turrails: "https://rubyonrails.org/"
  new: "https://news.railstutorial.org/"
  lu: "luffy.jpg"
user:
  email:
    length: 255
    regex: !ruby/regexp '/\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i'
  name:
    length: 50
  password:
    length: 6
