url:
  turhome: "https://www.railstutorial.org"
  turhelp: "https://www.railstutorial.org/help"
  turbook: "https://www.railstutorial.org/book"
  mich: "https://www.michaelhartl.com/"
  Learn: "https://www.learnenough.com/"
  screen: "https://screencasts.railstutorial.org/"
  turrails: "https://rubyonrails.org/"
  new: "https://news.railstutorial.org/"
  lu: "luffy.jpg"
  change: "https://gravatar.com/emails"
user:
  email:
    length: 255
    regex: !ruby/regexp '/\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i'
  name:
    length: 50
  password:
    length: 6
  expired:
    time: 2
gravatar:
  size: 80
  size_index: 50
paging:
  size: 10
image:
  accept_types: "image/jpeg,image/gif,image/png"
  height: 500
  size: 5
  types: ["image/jpeg", "image/gif", "image/png"]
  width: 500
micropost:
  content:
    length: 140
