url:
  turhome: "https://www.railstutorial.org"
  turhelp: "https://www.railstutorial.org/help"
  turbook: "https://www.railstutorial.org/book"
  mich: "https://www.michaelhartl.com/"
  Learn: "https://www.learnenough.com/"
  screen: "https://screencasts.railstutorial.org/"
  turrails: "https://rubyonrails.org/"
  new: "https://news.railstutorial.org/"
  lu: "luffy.jpg"
